import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import API from '../api/axios';
import { 
  Loader2, 
  CheckCircle2, 
  AlertCircle, 
  ArrowLeft, 
  ShieldCheck,
  Copy,
  ExternalLink
} from 'lucide-react';

const Ballot = () => {
  const { electionId } = useParams();
  const navigate = useNavigate();
  
  const [candidates, setCandidates] = useState([]);
  const [election, setElection] = useState(null);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [selectedCandidate, setSelectedCandidate] = useState(null);
  const [receipt, setReceipt] = useState(null); // State for the success modal

  useEffect(() => {
    const fetchBallotData = async () => {
      try {
        setLoading(true);
        // Fetch Election details and Candidates in parallel
        const [electionRes, candidateRes] = await Promise.all([
          API.get(`/elections/${electionId}`),
          API.get(`/candidates/election/${electionId}`) 
        ]);
        setElection(electionRes.data);
        setCandidates(candidateRes.data);
      } catch (err) {
        console.error("Ballot Fetch Error:", err);
      } finally {
        setLoading(false);
      }
    };
    if (electionId) fetchBallotData();
  }, [electionId]);

  const handleVoteSubmission = async () => {
    if (!selectedCandidate) return;

    const confirmVote = window.confirm(
      "Are you sure? This vote will be encrypted and cannot be reversed."
    );
    if (!confirmVote) return;

    setSubmitting(true);
    try {
      // ✅ FIXED: Changed endpoint to '/vote/cast' to match your backend route
      const res = await API.post('/vote/cast', {
        electionId,
        candidateId: selectedCandidate
      });

      // Show the receipt hash generated by your backend
      setReceipt(res.data.receipt);
    } catch (err) {
      console.error("Voting Error:", err);
      const errorMsg = err.response?.data?.msg || "An error occurred while casting your vote.";
      alert(errorMsg);
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) return (
    <div className="flex h-screen flex-col items-center justify-center bg-slate-50">
      <Loader2 className="animate-spin text-blue-600 mb-2" size={40} />
      <p className="text-slate-500 font-medium">Preparing Secure Ballot...</p>
    </div>
  );

  return (
    <div className="min-h-screen bg-slate-50 p-6">
      <div className="max-w-2xl mx-auto">
        <button 
          onClick={() => navigate('/dashboard')} 
          className="flex items-center gap-2 text-slate-500 hover:text-blue-600 mb-6 transition-colors font-medium border-none bg-transparent cursor-pointer"
        >
          <ArrowLeft size={18} /> Exit to Dashboard
        </button>

        <div className="bg-white rounded-3xl p-8 shadow-xl border border-slate-200">
          <div className="text-center mb-8">
            <div className="flex justify-center mb-4">
              <div className="bg-blue-50 p-3 rounded-full text-blue-600">
                <ShieldCheck size={32} />
              </div>
            </div>
            <h1 className="text-3xl font-black text-slate-900">Official Ballot</h1>
            <p className="text-blue-600 font-bold mt-1 uppercase tracking-tight">
              {election?.title || "Active Election"}
            </p>
            <p className="text-slate-500 mt-2">Please select your preferred candidate below.</p>
          </div>

          <div className="space-y-4">
            {candidates.length > 0 ? (
              candidates.map((candidate) => (
                <div 
                  key={candidate._id}
                  onClick={() => !submitting && setSelectedCandidate(candidate._id)}
                  className={`relative p-5 rounded-2xl border-2 cursor-pointer transition-all flex items-center justify-between ${
                    selectedCandidate === candidate._id 
                    ? "border-blue-600 bg-blue-50/50 ring-4 ring-blue-50" 
                    : "border-slate-100 hover:border-blue-200 bg-slate-50/30"
                  } ${submitting ? "opacity-50 cursor-not-allowed" : ""}`}
                >
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 bg-white rounded-xl shadow-sm flex items-center justify-center text-xl font-bold text-slate-400 uppercase">
                      {candidate.name.charAt(0)}
                    </div>
                    <div>
                      <h3 className="font-bold text-slate-900">{candidate.name}</h3>
                      <p className="text-xs font-bold text-blue-600 uppercase tracking-widest">
                        {candidate.party}
                      </p>
                    </div>
                  </div>
                  {selectedCandidate === candidate._id && (
                    <CheckCircle2 className="text-blue-600" size={24} />
                  )}
                </div>
              ))
            ) : (
              <div className="text-center py-12 border-2 border-dashed border-slate-200 rounded-2xl">
                <AlertCircle className="mx-auto text-slate-300 mb-3" size={40} />
                <p className="text-slate-500 font-medium">No Candidates Found</p>
              </div>
            )}
          </div>

          <button 
            onClick={handleVoteSubmission}
            disabled={!selectedCandidate || submitting}
            className="w-full mt-8 bg-blue-600 hover:bg-blue-700 text-white font-bold py-4 rounded-2xl transition-all shadow-lg shadow-blue-200 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-3"
          >
            {submitting ? (
              <>
                <Loader2 className="animate-spin" size={20} />
                Encrypting & Casting...
              </>
            ) : (
              "Cast Secure Vote"
            )}
          </button>
        </div>
      </div>

      {/* --- SUCCESS RECEIPT MODAL --- */}
      {receipt && (
        <div className="fixed inset-0 bg-slate-900/80 backdrop-blur-sm flex items-center justify-center p-4 z-[100]">
          <div className="bg-white rounded-3xl p-8 max-w-md w-full text-center shadow-2xl">
            <div className="w-20 h-20 bg-green-100 text-green-600 rounded-full flex items-center justify-center mx-auto mb-6">
              <CheckCircle2 size={48} />
            </div>
            <h2 className="text-2xl font-bold text-slate-900 mb-2">Vote Cast Successfully!</h2>
            <p className="text-slate-500 mb-6">Your vote has been encrypted and recorded on the secure ledger.</p>
            
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-100 mb-6">
              <p className="text-[10px] uppercase font-bold text-slate-400 tracking-widest mb-2">Digital Receipt Hash</p>
              <code className="text-xs break-all text-blue-600 font-mono font-bold">
                {receipt}
              </code>
            </div>

            <button 
              onClick={() => navigate('/dashboard')}
              className="w-full bg-slate-900 text-white font-bold py-3 rounded-xl hover:bg-slate-800 transition-all"
            >
              Return to Dashboard
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default Ballot;